org: myorgluis
service: appoinment

provider:
  name: aws
  runtime: nodejs20.x
  
plugins:
  - serverless-offline

functions:
  appointment:
    handler: src/Interfaces/Http/appointment.router
    events:
      - httpApi:
          path: /appointments
          method: post
      - httpApi:
          path: /appointments/{insuredId}
          method: get