org: myorgluis
service: appoinment

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  httpApi:
    cors: true
  environment:
    DDB_TABLE: AppointmentsTable
    APPOINTMENT_TOPIC_ARN: !Ref AppointmentTopic  
    EVENT_BUS_NAME: default
    # --- Conexión a MySQL para Perú
    PE_DB_HOST: dbappointment.c2jccqskykox.us-east-1.rds.amazonaws.com
    PE_DB_PORT: "3306"
    PE_DB_USER: admin
    PE_DB_PASS: "Softtek#2023"
    PE_DB_NAME: app_pe

    # --- Conexión a MySQL para Chile ---
    CL_DB_HOST: dbappointment.c2jccqskykox.us-east-1.rds.amazonaws.com
    CL_DB_PORT: "3306"
    CL_DB_USER: admin
    CL_DB_PASS: "Softtek#2023"
    CL_DB_NAME: app_cl
  iam:
    role:
      statements:
        # DynamoDB
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:GetItem
            - dynamodb:Query
          Resource:
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/AppointmentsTable
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/AppointmentsTable/index/InsuredGSI
        # SNS
        - Effect: Allow
          Action: sns:Publish
          Resource: !Ref AppointmentTopic
        
        # EventBridge
        - Effect: Allow
          Action: events:PutEvents
          Resource: "*"

plugins:
  - serverless-offline

functions:
  appointment:
    handler: src/Interfaces/Http/appointment.router
    events:
      - httpApi:
          path: /appointments
          method: post
      - httpApi:
          path: /appointments/{insuredId}
          method: get
      - sqs:
          arn: { Fn::GetAtt: [ ConfirmationQueue, Arn ] }
          batchSize: 1
  appointment_pe:
    handler: src/Interfaces/Workers/appointment_pe.handler
    events:
      - sqs:
          arn: { Fn::GetAtt: [ SqsPE, Arn ] }
          batchSize: 1
          maximumBatchingWindow: 0
  appointment_cl:
    handler: src/Interfaces/Workers/appointment_cl.handler
    events:
      - sqs:
          arn: { Fn::GetAtt: [ SqsCL, Arn ] }
          batchSize: 1
          maximumBatchingWindow: 0
  docs:
    handler: src/Interfaces/Http/docs.handler
    events:
      - httpApi:
          path: /docs
          method: get  

resources:
  Resources:
    # DynamoDB
    AppointmentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AppointmentsTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: appointmentId
            AttributeType: S
          - AttributeName: insuredId
            AttributeType: S
        KeySchema:
          - AttributeName: appointmentId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: InsuredGSI
            KeySchema:
              - AttributeName: insuredId
                KeyType: HASH
            Projection:
              ProjectionType: ALL

    # SNS Topic
    AppointmentTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: appointment-topic

    # --- SQS por país ---
    SqsPE:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: SQS_PE

    SqsCL:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: SQS_CL

    # --- Suscripciones SNS -> SQS con filtro por countryISO ---
    SnsSubPE:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: !Ref AppointmentTopic
        Protocol: sqs
        Endpoint: !GetAtt SqsPE.Arn
        FilterPolicy:
          countryISO: [ "PE" ]

    SnsSubCL:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: !Ref AppointmentTopic
        Protocol: sqs
        Endpoint: !GetAtt SqsCL.Arn
        FilterPolicy:
          countryISO: [ "CL" ]

    # --- Policies para permitir a SNS enviar a SQS ---
    SqsPEPolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues: [ !Ref SqsPE ]
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal: { Service: sns.amazonaws.com }
              Action: SQS:SendMessage
              Resource: !GetAtt SqsPE.Arn
              Condition:
                ArnEquals:
                  aws:SourceArn: !Ref AppointmentTopic

    SqsCLPolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues: [ !Ref SqsCL ]
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal: { Service: sns.amazonaws.com }
              Action: SQS:SendMessage
              Resource: !GetAtt SqsCL.Arn
              Condition:
                ArnEquals:
                  aws:SourceArn: !Ref AppointmentTopic
              
    ConfirmationQueue:
      Type: AWS::SQS::Queue
      Properties: { QueueName: SQS_CONFIRMATION }

    AppointmentConfirmedRule:
      Type: AWS::Events::Rule
      Properties:
        Name: appointment-confirmed-rule
        EventBusName: default
        EventPattern:
          source: [ "rimac.appointment" ]
          detail-type: [ "AppointmentConfirmed" ]
        Targets:
          - Arn: !GetAtt ConfirmationQueue.Arn
            Id: ConfirmationTarget

    ConfirmationQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues: [ !Ref ConfirmationQueue ]
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal: { Service: events.amazonaws.com }
              Action: SQS:SendMessage
              Resource: !GetAtt ConfirmationQueue.Arn